config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admins/", admin.site.urls),
    path("", include("manager.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path

from .views import (
    index,
    HotelListView,
    RouteListView,
    TripListView,
    TicketListView,
    HotelDetailView,
    TicketDeleteView,
    RouteDetailView,
    TripDetailView,
    TicketDetailView,
    TicketCreateView,
    UserCreateView,
    UserUpdateView,
    password_change,
)

urlpatterns = [
    path("", index, name="index"),
    path("hotels/", HotelListView.as_view(), name="hotel-list"),
    path("routes/", RouteListView.as_view(), name="route-list"),
    path("trips/", TripListView.as_view(), name="trip-list"),
    path("tickets/", TicketListView.as_view(), name="ticket-list"),
    path("hotels/<int:pk>/", HotelDetailView.as_view(), name="hotel-detail"),
    path("routes/<int:pk>/", RouteDetailView.as_view(), name="route-detail"),
    path("trips/<int:pk>/", TripDetailView.as_view(), name="trip-detail"),
    path("tickets/<int:pk>/", TicketDetailView.as_view(), name="ticket-detail"),
    path(
        "trips/<int:trip_pk>/tickets/create/",
        TicketCreateView.as_view(),
        name="ticket-create",
    ),
    path("accounts/register/", UserCreateView.as_view(), name="register"),
    path("tickets/<int:pk>/delete/", TicketDeleteView.as_view(), name="ticket-delete"),
    path("accounts/<int:pk>/profile/", UserUpdateView.as_view(), name="profile"),
    path("accounts/password_change/", password_change, name="password-change"),
]

app_name = "manager"

manager/models.py
import secrets

from django.db import models
from django.contrib.auth.models import User


class Hotel(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField()

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.name


class Trip(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    hotel = models.ManyToManyField(Hotel, related_name="trips")

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.title


class Route(models.Model):
    departure = models.CharField(max_length=50)
    arrival = models.CharField(max_length=50)
    duration = models.DurationField()
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name="routes")

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return f"{self.departure} - {self.arrival}"


class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    route = models.ForeignKey(Route, on_delete=models.CASCADE, related_name="tickets")
    date = models.DateField()
    number = models.AutoField(primary_key=True, default=secrets.randbits(15))
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return f"{self.number} - {self.user.username}"

manager/forms.py
import datetime
from django.contrib.auth.forms import SetPasswordForm

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from manager.models import Ticket, Route, Hotel


class DateInput(forms.DateInput):
    input_type = "date"


class TicketForm(forms.ModelForm):
    hotel = forms.ModelChoiceField(queryset=Hotel.objects.none())
    date = forms.DateField(widget=DateInput(attrs={"type": "date"}))

    class Meta:
        model = Ticket
        fields = ("route", "hotel", "date")

    def __init__(self, *args, **kwargs):
        trip_pk = kwargs.pop("trip_pk")
        super().__init__(*args, **kwargs)
        self.fields["route"].queryset = Route.objects.filter(trip__pk=trip_pk)
        self.fields["hotel"].queryset = Hotel.objects.filter(trips__pk=trip_pk)
        self.fields["route"].widget.attrs.update(
            {
                "class": "js-example-basic-single js-states form-control",
                "style": "width: 100%;",
            }
        )
        self.fields["hotel"].widget.attrs.update(
            {
                "class": "js-example-basic-single js-states form-control",
                "style": "width: 100%;",
            }
        )
        self.fields["date"].widget.attrs.update(
            {
                "class": "form-control",
                "id": "pro-bootstrap-date-departure",
                "placeholder": "",
                "type": "text",
            }
        )

    def clean_date(self):
        date = self.cleaned_data["date"]
        if date < datetime.date.today():
            raise forms.ValidationError("Date cannot be in the past!")
        return date


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "email")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Username"}
        )
        self.fields["password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Password"}
        )
        self.fields["password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Confirm Password"}
        )
        self.fields["first_name"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "First Name",
            }
        )
        self.fields["last_name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Last Name"}
        )
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Email"}
        )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "First Name",
                "value": user.first_name,
            }
        )
        self.fields["last_name"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Last Name",
                "value": user.last_name,
            }
        )
        self.fields["email"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Email",
                "value": user.email,
            }
        )
        self.fields["username"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Username",
                "value": user.username,
            }
        )

    def clean_email(self):
        email = self.cleaned_data["email"]
        if (
            User.objects.filter(email=email)
            .exclude(username=self.instance.username)
            .exists()
        ):
            raise forms.ValidationError("Email already exists!")
        return email

    def clean_username(self):
        username = self.cleaned_data["username"]
        if (
            User.objects.filter(username=username)
            .exclude(username=self.instance.username)
            .exists()
        ):
            raise forms.ValidationError("Username already exists!")
        return username


class PasswordChangeForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ["new_password1", "new_password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["new_password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Password"}
        )
        self.fields["new_password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Confirm Password"}
        )


class TripSearchForm(forms.Form):
    title = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-lg form-control-borderless",
                "type": "text",
                "placeholder": "Search",
                "aria-label": "Search",
            }
        ),
    )


class HotelSearchForm(forms.Form):
    name = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-lg form-control-borderless",
                "type": "text",
                "placeholder": "Search",
                "aria-label": "Search",
            }
        ),
    )


class RoutesSearchForm(forms.Form):
    departure = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-lg form-control-borderless",
                "type": "text",
                "placeholder": "Departure",
                "aria-label": "Search",
            }
        ),
    )
    arrival = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "class": "form-control form-control-lg form-control-borderless",
                "type": "text",
                "placeholder": "Arrival",
            }
        ),
    )

manager/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView


from manager.forms import (
    TicketForm,
    UserCreateForm,
    UserUpdateForm,
    PasswordChangeForm,
    TripSearchForm,
    HotelSearchForm,
    RoutesSearchForm,
)
from manager.models import Hotel, Route, Trip, Ticket


@login_required
def index(request: HttpRequest) -> HttpResponse:
    return render(request, "manager/index.html")


class HotelListView(LoginRequiredMixin, generic.ListView):
    model = Hotel
    template_name = "manager/hotel_list.html"
    context_object_name = "hotels"
    paginate_by = 6
    queryset = Hotel.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HotelListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search"] = HotelSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        form = HotelSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(name__icontains=form.cleaned_data["name"])

        return self.queryset.all()


class RouteListView(LoginRequiredMixin, generic.ListView):
    model = Route
    template_name = "manager/route_list.html"
    context_object_name = "routes"
    paginate_by = 6
    queryset = Route.objects.select_related("trip")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RouteListView, self).get_context_data(**kwargs)

        arrival = self.request.GET.get("arrival", "")
        departure = self.request.GET.get("departure", "")

        context["search"] = RoutesSearchForm(
            initial={"arrival": arrival, "departure": departure}
        )

        return context

    def get_queryset(self):
        form = RoutesSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                arrival__icontains=form.cleaned_data["arrival"],
                departure__icontains=form.cleaned_data["departure"],
            )

        return self.queryset.all()


class TripListView(LoginRequiredMixin, generic.ListView):
    model = Trip
    paginate_by = 6
    queryset = Trip.objects.prefetch_related("hotel")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TripListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search"] = TripSearchForm(initial={"title": title})

        return context

    def get_queryset(self):
        form = TripSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(title__icontains=form.cleaned_data["title"])

        return self.queryset.all()


class TicketListView(LoginRequiredMixin, generic.ListView):
    model = Ticket

    def get_queryset(self):
        return Ticket.objects.filter(user=self.request.user)


class HotelDetailView(LoginRequiredMixin, generic.DetailView):
    model = Hotel
    template_name = "manager/hotel_detail.html"


class RouteDetailView(LoginRequiredMixin, generic.DetailView):
    model = Route
    template_name = "manager/route_detail.html"


class TripDetailView(LoginRequiredMixin, generic.DetailView):
    model = Trip


class TicketDetailView(LoginRequiredMixin, generic.DetailView):
    model = Ticket


class TicketCreateView(LoginRequiredMixin, CreateView):
    model = Ticket
    form_class = TicketForm
    template_name = "manager/ticket_create.html"
    success_url = reverse_lazy("manager:ticket-detail")

    def form_valid(self, form):
        # Set the current user as the ticket's user
        form.instance.user = self.request.user

        # Set the ticket's route based on the selected trip
        trip_pk = self.kwargs["trip_pk"]
        trip = get_object_or_404(Trip, pk=trip_pk)
        form.instance.route = trip.routes.first()

        # calculate the ticket's price
        hotel_price = form.cleaned_data["hotel"].price
        trip_price = trip.price
        form.instance.price = hotel_price + trip_price
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["trip_pk"] = self.kwargs["trip_pk"]
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        trip_pk = self.kwargs["trip_pk"]
        trip = get_object_or_404(Trip, pk=trip_pk)
        context["trip"] = trip
        context["routes"] = trip.routes.all()
        context["hotels"] = Hotel.objects.filter(trips=trip)
        return context

    def get_success_url(self):
        return reverse_lazy("manager:ticket-detail", kwargs={"pk": self.object.pk})


class UserCreateView(CreateView):
    template_name = "registration/signup.html"
    form_class = UserCreateForm
    success_url = reverse_lazy("manager:index")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("manager:index")


class TicketDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ticket
    success_url = reverse_lazy("manager:ticket-list")


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = "registration/profile.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy("manager:profile", kwargs={"pk": self.object.pk})

    def get_queryset(self):
        return User.objects.filter(pk=self.request.user.pk)

    # add success message to context if form is valid
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == "GET" and self.request.GET.get("success") == "True":
            if self.object:
                messages.success(self.request, "Profile updated successfully")
                context["messages"] = messages.get_messages(self.request)
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        response["Location"] += "?success=True"
        return response


@login_required
def password_change(request: HttpRequest) -> HttpResponse:
    user = request.user
    if request.method == "POST":
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    form = PasswordChangeForm(user, request.POST)

    return render(request, "registration/password_change.html", {"form": form})

templates/manager/hotel_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5" id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">
        <div class="col-md-12">
          <h1 class="heading mb-3 display-4 font-light probootstrap-animate" style="color: white">Hotel «{{ hotel.name }}»</h1>
        </div>
      </div>
    </div>
  </section>
  <div class="container my-5">
    <div class="row">
      <div class="col-md-12">
        <h1 class="mb-3">Address: {{ hotel.address}}</h1>
        <h4 class="mb-3">Price: {{ hotel.price }}$</h4>
        <h4 class="mb-3">Description:</h4>
        <div style="word-wrap: break-word">
          <p style="padding-left: 40px; color: black">{{ hotel.description }}</p>
        </div>
        <hr>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-md-12">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Trip</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
                {% for trip in hotel.trips.all %}
                  <tr>
                    <td><a href="{% url 'manager:trip-detail' pk=trip.pk %}">{{ trip.title }}</a></td>
                    <td>{{ trip.price }}</td>
                  </tr>
                {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

templates/manager/hotel_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5" id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row align-items-center text-center">
        <div class="col-md">
          <h2 class="heading mb-2 display-4 font-light probootstrap-animate">Hotels</h2>
        </div>
      </div>
    </div>
  </section>
  <!-- END section -->

  <section class="probootstrap_section" id="section-city-guides">
    <div class="container">
     {% include "includes/search.html" %}
      <div class="row mb-3">
        <div class="row">
          {% for hotel in hotels %}
            <div class="col-md-6" >
              <div class="media probootstrap-media d-flex align-items-stretch mb-4 probootstrap-animate">
                <div class="media-body" style="word-wrap: break-word !important; white-space: normal">
                  <h5 class="mb-3"><a href="{% url 'manager:hotel-detail' pk=hotel.pk %}">{{ hotel.pk }}. {{ hotel.name }}</a></h5>
                  <div>
                    <p>Price: {{ hotel.price }}$</p>
                  </div>
                </div>
              </div>
            </div>
            {% if forloop.counter|divisibleby:2 and not forloop.last %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
        {% include 'includes/pagination.html' %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5"  id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md">
          <h2 class="heading mb-2 display-4 font-light probootstrap-animate">Explore The World With Ease</h2>
          <br>
          <p class="lead mb-5 probootstrap-animate">
            <a href="{% url 'manager:trip-list' %}" role="button" class="btn btn-primary p-3 mr-3 pl-5 pr-5 text-uppercase d-lg-inline d-md-inline d-sm-block d-block mb-3">Choose your trip!</a>
          </p>
        </div>
        </div>
      </div>
  </section>
  <!-- END section -->
{% endblock %}

templates/manager/route_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5" id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row align-items-center text-center">
        <div class="col-md">
          <h2 class="heading mb-2 display-4 font-light probootstrap-animate">Route #{{ route.pk }}</h2>
        </div>
      </div>
    </div>
  </section>
  <div class="container my-5">
    <div class="row">
      <div class="col-md-12">
        <h1 class="mb-3">From: <strong>{{ route.departure }}</strong></h1>
        <h1 class="mb-3">To: <strong>{{ route.arrival }}</strong></h1>
        <h3 class="mb-3">Duration: {{ route.duration }}</h3>
        <h3 class="mb-3">Trip: <a href="{% url 'manager:trip-detail' pk=route.trip.pk %}">{{ route.trip }}</a></h3>
      </div>
    </div>
  </div>
{% endblock %}

templates/manager/route_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Routes{% endblock %}

{% block content %}
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5" id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row text-center mb-5 probootstrap-animate">
        <div class="col-md-12">
          <h2 class="display-1 border-bottom probootstrap-section-heading">Routes</h2>
        </div>
      </div>
    </div>
  </section>
  <section class="probootstrap_section" id="section-city-guides">
    <div class="container">
      {% include "includes/search.html" %}
      <div class="row mb-3">
        <div class="row">
          {% for route in routes %}
            <div class="col-md-6" >
              <div class="media probootstrap-media d-flex align-items-stretch mb-4 probootstrap-animate">
                <div class="media-body" style="word-wrap: break-word !important; white-space: normal">
                  <h5 class="mb-3"><a href="{% url 'manager:route-detail' pk=route.pk %}">{{ route.pk }}: {{ route.departure }} - {{ route.arrival }}</a></h5>
                  <div>
                    <p>Trip: {{ route.trip }}</p>
                  </div>
                </div>
              </div>
            </div>
            {% if forloop.counter|divisibleby:2 and not forloop.last %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
        {% include 'includes/pagination.html' %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/ticket_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5" id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row text-center mb-5 probootstrap-animate">
        <div class="col-md-12">
          <form method="post" action="" class="probootstrap-animate">
            {% csrf_token %}
            <h2 class="display-1 border-bottom probootstrap-section-heading">Are you sure you want to delete this ticket?</h2>
            <button type="submit" class="btn btn-primary btn-danger">Yes</button>
            <a href="{% url 'manager:ticket-detail' pk=ticket.pk %}" class="btn btn-primary btn-success">Back</a>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/ticket_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5" id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">
        <div class="col-md-12">
          <h1 class="heading mb-3 display-4 font-light probootstrap-animate" style="color: white">Ticket #{{ ticket.number }}</h1>
          <a href="{% url 'manager:ticket-delete' pk=ticket.pk %}" class="btn btn-primary btn-danger probootstrap-animate">Delete</a>
        </div>
      </div>
    </div>
  </section>
  <br>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="mb-3">Route: <a href="{% url 'manager:route-detail' pk=ticket.route.id %}">{{ ticket.route.id }}</a></h1>
          <h4 class="mb-3">Date: {{ ticket.date|date:"F j, Y" }}</h4>
          <h4 class="mb-3">User data: {{ ticket.user.first_name }} {{ ticket.user.last_name }}</h4>
        </div>
        <div class="col-md-6">
          <h1 class="mb-3"></h1>
          <h1 class="mb-3">Trip: <a href="{% url 'manager:trip-detail' pk=ticket.route.trip.pk %}">{{ ticket.route.trip.title }}</a></h1>
          <h4 class="mb-3">Total price: {{ ticket.price }}$</h4>
        </div>
      </div>
    </div>
{% endblock %}

templates/manager/trip_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5" id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row align-items-center text-center">
        <div class="col-md">
          <h2 class="heading mb-2 display-4 font-light probootstrap-animate">Trip #{{ trip.pk }}</h2>
          <p class="lead mb-5 probootstrap-animate"><a href="{% url 'manager:ticket-create' trip_pk=trip.pk%}" class="btn btn-primary">Buy</a></p>
        </div>
      </div>
    </div>
  </section>
  <br>
    <div class="container display-4">
    <div class="row">
      <div class="col-md-6">
        <h1 class="mb-3">Title: {{ trip.title}}</h1>
        <h2 class="mb-3">Price: {{ trip.price }}</h2>
        <div class="mb-3" style="word-wrap: break-word">
          <h3 class="mb-3">Description:</h3>
          <p style="font-size: 24px; padding-left: 40px">{{ trip.description }}</p>
        </div>
      </div>
      <div class="col-md-6">
        <h3 class="mb-3">Hotels:</h3>
        <ul class="list-unstyled mb-3">
          {% for hotel in trip.hotel.all %}
          <li class="mb-3">
            <p style="font-size: 24px; padding-left: 40px"><a href="{% url 'manager:hotel-detail' pk=hotel.pk %}">{{ hotel }}</a></p>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/manager/trip_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('{% static "images/bg_1.jpg" %}');" data-stellar-background-ratio="0.5" id="section-home">
    <div class="overlay"></div>
    <div class="container">
      <div class="row align-items-center text-center">
        <div class="col-md">
          <h2 class="heading mb-2 display-4 font-light probootstrap-animate">Choose your trip!</h2>
        </div>
      </div>
    </div>
  </section>
  <!-- END section -->

  <section class="probootstrap_section" id="section-city-guides">
    <div class="container">
      <div class="row mb-3">
      {% include "includes/search.html" %}
        <div class="row">
          {% if trip_list|length == 0 %}
            <div class="col-md-12">
              <div class="media probootstrap-media d-flex align-items-stretch mb-4 probootstrap-animate">
                <div class="media-body">
                  <h5 class="mb-3">No trips found</h5>
                </div>
              </div>
            </div>
          {% endif %}
          {% for trip in trip_list %}
            <div class="col-md-6" >
              <div class="media probootstrap-media d-flex align-items-stretch mb-4 probootstrap-animate">
                <div class="media-body" style="word-wrap: break-word !important; white-space: normal">
                  <h5 class="mb-3"><a href="{% url 'manager:trip-detail' pk=trip.id %}">{{ trip.id }}. {{ trip.title }}</a></h5>
                  <div>
                    <p>{{ trip.description }}</p>
                  </div>
                </div>
              </div>
            </div>
            {% if forloop.counter|divisibleby:2 and not forloop.last %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
          {% include "includes/pagination.html" %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}