config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admins/", admin.site.urls),
    path("", include("manager.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path

from .views import (
    index,
    HotelListView,
    RouteListView,
    TripListView,
    TicketListView,
    HotelDetailView,
    TicketDeleteView,
    RouteDetailView,
    TripDetailView,
    TicketDetailView,
    TicketCreateView,
    UserCreateView,
    UserUpdateView,
    password_change,
)

urlpatterns = [
    path("", index, name="index"),
    path("hotels/", HotelListView.as_view(), name="hotel-list"),
    path("routes/", RouteListView.as_view(), name="route-list"),
    path("trips/", TripListView.as_view(), name="trip-list"),
    path("tickets/", TicketListView.as_view(), name="ticket-list"),
    path("hotels/<int:pk>/", HotelDetailView.as_view(), name="hotel-detail"),
    path("routes/<int:pk>/", RouteDetailView.as_view(), name="route-detail"),
    path("trips/<int:pk>/", TripDetailView.as_view(), name="trip-detail"),
    path("tickets/<int:pk>/", TicketDetailView.as_view(), name="ticket-detail"),
    path(
        "trips/<int:trip_pk>/tickets/create/",
        TicketCreateView.as_view(),
        name="ticket-create",
    ),
    path("accounts/register/", UserCreateView.as_view(), name="register"),
    path("tickets/<int:pk>/delete/", TicketDeleteView.as_view(), name="ticket-delete"),
    path("accounts/<int:pk>/profile/", UserUpdateView.as_view(), name="profile"),
    path("accounts/password_change/", password_change, name="password-change"),
]

app_name = "manager"

templates/includes/footer.html
<footer class="probootstrap_section probootstrap-border-top">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-3">
        <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
        <ul class="list-unstyled">
          <li><a href="/" target="_blank">Home</a></li>
          <li><a href="{% url 'manager:trip-list' %}" target="_blank">Trips</a></li>
          <li><a href="{% url 'manager:hotel-list' %}" target="_blank">Hotels</a></li>
          <li><a href="{% url 'manager:route-list' %}" target="_blank">Routes</a></li>
        </ul>
      </div>
    </div>
    <div class="row pt-5">
      <div class="col-md-12 text-center">
        <p class="probootstrap_font-14">&copy; 2023. All Rights Reserved. <br> Designed &amp; Developed by <a href="https://probootstrap.com/" target="_blank">ProBootstrap</a><small> (Don't remove credit link on this footer. See <a href="https://probootstrap.com/license/">license</a>)</small></p>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark probootstrap_navbar" id="probootstrap-navbar">
  <div class="container">
    <a class="navbar-brand" href="/">Travel manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-menu" aria-controls="probootstrap-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span><i class="ion-navicon"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="probootstrap-menu">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'manager:trip-list' %}">Trips</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'manager:hotel-list' %}">Hotels</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'manager:route-list' %}">Routes</a></li>

        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link" style="color: white">Welcome, <a href="{% url 'manager:profile' pk=user.pk %}">{{ user.username }}</a></span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'manager:ticket-list' %}">My ticket</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Log in</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}

  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?{% query_transform request page=i %}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
      {% endif %}
    {% endif %}
    </ul>
  </nav>

templates/includes/search.html
<div class="col-md-12 text-center probootstrap-animate">
  <form action="" method="get" class="form-inline">
    {{ search }}
    <input type="submit" value="🔍" class="btn btn-primary">
  </form>
  <br>
  <br>
</div>